
name: Cypress2

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Cypress
        uses: actions/checkout@v3
        with:
          deno-version: v1.x


      - name: Installing Cypress
        run: npm i

      - name: Running Cypress Test
        run: npx cypress run
